name             "alfresco"
maintainer       "Maurizio Pillitu"
maintainer_email ""
license          "Apache 2.0"
description      "Installs Alfresco Community and Enterprise Edition."
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.5.0"

depends "artifact-deployer", "=0.8.6"
depends "imagemagick"
depends "file"
depends "java"
depends "mysql"
depends 'mysql2_chef_gem'
depends "database"
depends "openoffice"
depends "swftools"
depends "tomcat"
depends "haproxy"
depends "build-essential"
depends "iptables"
depends "yum-epel"
